### ISSUE TITLE
[Feature Request] Dependabot Support for Nim Package Ecosystem

### ISSUE THREAD

**Issue by kevinmatthes** [nim-lang/RFCs#494]
### Abstract

The Nim package ecosystem should be added to Dependabot version updates.  Is this already planned / in development?

### Motivation

Since Nim projects can have Nim libraries as their dependencies, their versions need to be kept up-to-date.  Dependabot helps to do so.  All Nim developers using GitHub would benefit.

### Description

Dependabot is a bot for GitHub to automatically check for version updates to dependencies, written in Ruby.  It is maintained here:  https://github.com/dependabot/dependabot-core.  Dependabot already supports numerous package ecosystems; unfortunately, Nim does not belong to this set.  I would like to ask for adding it.

### Code Examples

When implemented, Dependabot might check for Nim dependencies with a configuration similar to the following.

```yaml
version: 2
updates:
  - package-ecosystem: nimble
    directory: /
    schedule:
      interval: daily
      time: '00:00'
```

### Backwards Compatibility

There should not be problems with backwards compatibility.
